/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import config.HibernateConfig;
import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.JPanel;
import javax.swing.UIDefaults;
import javax.swing.UIManager;
import view.component.HighlightPanel;
import view.component.ScrollBarWin11UI;
import view.page.ThanhVienPage;
import view.page.ThanhVienPage1;
import view.page.ThietBiPage;
import view.page.ThongKePage;
import view.page.ThongTinSDPage;
import view.page.ViPhamPage;

/**
 *
 * @author Bum
 */
public class mainLayout extends javax.swing.JFrame {

    /**
     * Creates new form mainLayout
     */
    public mainLayout() {
        setTheme();
        UIDefaults ui = UIManager.getDefaults();
        ui.put("ScrollBarUI",ScrollBarWin11UI.class.getCanonicalName());
        HibernateConfig.getSessionFactory();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        app = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        imageIcon15 = new view.component.imageIcon();
        imageIcon16 = new view.component.imageIcon();
        body = new javax.swing.JPanel();
        menuBar = new javax.swing.JPanel();
        deviceOp = new view.component.HighlightPanel();
        jLabel3 = new javax.swing.JLabel();
        imageIcon5 = new view.component.imageIcon();
        userOp = new view.component.HighlightPanel();
        imageIcon2 = new view.component.imageIcon();
        jLabel1 = new javax.swing.JLabel();
        statisticOp = new view.component.HighlightPanel();
        imageIcon4 = new view.component.imageIcon();
        jLabel2 = new javax.swing.JLabel();
        checkinOp = new view.component.HighlightPanel();
        jLabel4 = new javax.swing.JLabel();
        imageIcon6 = new view.component.imageIcon();
        bannedOp = new view.component.HighlightPanel();
        jLabel5 = new javax.swing.JLabel();
        imageIcon7 = new view.component.imageIcon();
        content = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));
        setUndecorated(true);
        setResizable(false);

        app.setBackground(new java.awt.Color(204, 204, 255));
        app.setLayout(new java.awt.BorderLayout());

        header.setBackground(new java.awt.Color(0, 102, 51));

        jLabel8.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Dashboard");

        imageIcon15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/switch.png"))); // NOI18N
        imageIcon15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imageIcon15MouseClicked(evt);
            }
        });

        imageIcon16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/remove.png"))); // NOI18N

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(576, 576, 576)
                .addComponent(imageIcon16, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(imageIcon15, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, headerLayout.createSequentialGroup()
                        .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(imageIcon16, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(imageIcon15, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        app.add(header, java.awt.BorderLayout.NORTH);

        body.setBackground(new java.awt.Color(204, 204, 255));
        body.setLayout(new java.awt.BorderLayout());

        menuBar.setBackground(new java.awt.Color(51, 51, 51));
        menuBar.setForeground(new java.awt.Color(102, 0, 153));
        menuBar.setPreferredSize(new java.awt.Dimension(200, 736));

        deviceOp.setColor(normal);
        deviceOp.setColorClick(click);
        deviceOp.setColorOver(hover);
        deviceOp.setRadius(0);
        deviceOp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deviceOpMouseClicked(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(187, 187, 187));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(188, 188, 188));
        jLabel3.setText("Thiết bị");

        imageIcon5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/settings.png"))); // NOI18N
        imageIcon5.setPreferredSize(new java.awt.Dimension(32, 32));

        javax.swing.GroupLayout deviceOpLayout = new javax.swing.GroupLayout(deviceOp);
        deviceOp.setLayout(deviceOpLayout);
        deviceOpLayout.setHorizontalGroup(
            deviceOpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deviceOpLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(imageIcon5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        deviceOpLayout.setVerticalGroup(
            deviceOpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deviceOpLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(deviceOpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(imageIcon5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        userOp.setColor(normal);
        userOp.setColorClick(click);
        userOp.setColorOver(hover);
        userOp.setRadius(0);
        userOp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userOpMouseClicked(evt);
            }
        });

        imageIcon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/contact.png"))); // NOI18N
        imageIcon2.setPreferredSize(new java.awt.Dimension(32, 32));

        jLabel1.setBackground(new java.awt.Color(187, 187, 187));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(188, 188, 188));
        jLabel1.setText("Thành viên");

        javax.swing.GroupLayout userOpLayout = new javax.swing.GroupLayout(userOp);
        userOp.setLayout(userOpLayout);
        userOpLayout.setHorizontalGroup(
            userOpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userOpLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(imageIcon2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        userOpLayout.setVerticalGroup(
            userOpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userOpLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(userOpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(imageIcon2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        statisticOp.setColor(normal);
        statisticOp.setColorClick(click);
        statisticOp.setColorOver(hover);
        statisticOp.setRadius(0);
        statisticOp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                statisticOpMouseClicked(evt);
            }
        });

        imageIcon4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/statistics.png"))); // NOI18N
        imageIcon4.setPreferredSize(new java.awt.Dimension(32, 32));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(188, 188, 188));
        jLabel2.setText("Tổng quát");

        javax.swing.GroupLayout statisticOpLayout = new javax.swing.GroupLayout(statisticOp);
        statisticOp.setLayout(statisticOpLayout);
        statisticOpLayout.setHorizontalGroup(
            statisticOpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statisticOpLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(imageIcon4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        statisticOpLayout.setVerticalGroup(
            statisticOpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statisticOpLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(statisticOpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imageIcon4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        checkinOp.setColor(normal);
        checkinOp.setColorClick(click);
        checkinOp.setColorOver(hover);
        checkinOp.setRadius(0);
        checkinOp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkinOpMouseClicked(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(187, 187, 187));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(188, 188, 188));
        jLabel4.setText("Check in");

        imageIcon6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/check-in.png"))); // NOI18N
        imageIcon6.setPreferredSize(new java.awt.Dimension(32, 32));

        javax.swing.GroupLayout checkinOpLayout = new javax.swing.GroupLayout(checkinOp);
        checkinOp.setLayout(checkinOpLayout);
        checkinOpLayout.setHorizontalGroup(
            checkinOpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(checkinOpLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(imageIcon6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        checkinOpLayout.setVerticalGroup(
            checkinOpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(checkinOpLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(checkinOpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(imageIcon6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bannedOp.setColor(normal);
        bannedOp.setColorClick(click);
        bannedOp.setColorOver(hover);
        bannedOp.setRadius(0);
        bannedOp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bannedOpMouseClicked(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(187, 187, 187));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(188, 188, 188));
        jLabel5.setText("Vi phạm");

        imageIcon7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/cancel.png"))); // NOI18N
        imageIcon7.setPreferredSize(new java.awt.Dimension(32, 32));

        javax.swing.GroupLayout bannedOpLayout = new javax.swing.GroupLayout(bannedOp);
        bannedOp.setLayout(bannedOpLayout);
        bannedOpLayout.setHorizontalGroup(
            bannedOpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bannedOpLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(imageIcon7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        bannedOpLayout.setVerticalGroup(
            bannedOpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bannedOpLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bannedOpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(imageIcon7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout menuBarLayout = new javax.swing.GroupLayout(menuBar);
        menuBar.setLayout(menuBarLayout);
        menuBarLayout.setHorizontalGroup(
            menuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuBarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(menuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(userOp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(deviceOp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(statisticOp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(checkinOp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bannedOp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        menuBarLayout.setVerticalGroup(
            menuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuBarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(statisticOp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userOp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deviceOp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkinOp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bannedOp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(486, Short.MAX_VALUE))
        );

        body.add(menuBar, java.awt.BorderLayout.WEST);

        content.setBackground(new java.awt.Color(204, 204, 255));
        content.setPreferredSize(new java.awt.Dimension(1166, 0));

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1166, Short.MAX_VALUE)
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 736, Short.MAX_VALUE)
        );

        body.add(content, java.awt.BorderLayout.CENTER);

        app.add(body, java.awt.BorderLayout.WEST);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(app, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(app, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void imageIcon15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imageIcon15MouseClicked
        System.exit(0);
    }//GEN-LAST:event_imageIcon15MouseClicked

    private void statisticOpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_statisticOpMouseClicked
        active(statisticOp);
        getContent(new ThanhVienPage1());
    }//GEN-LAST:event_statisticOpMouseClicked

    private void userOpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userOpMouseClicked
        active(userOp);
        getContent(new ThanhVienPage());
    }//GEN-LAST:event_userOpMouseClicked

    private void deviceOpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deviceOpMouseClicked
        active(deviceOp);
        getContent(new ThietBiPage());
    }//GEN-LAST:event_deviceOpMouseClicked

    private void checkinOpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkinOpMouseClicked
                active(checkinOp);
        getContent(new ThongTinSDPage());
    }//GEN-LAST:event_checkinOpMouseClicked

    private void bannedOpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bannedOpMouseClicked
                active(bannedOp);
        getContent(new ViPhamPage());
    }//GEN-LAST:event_bannedOpMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainLayout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainLayout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainLayout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainLayout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainLayout().setVisible(true);
            }
        });
    }
        public void getContent(JPanel panel){
        content.removeAll();
        content.setLayout(new BorderLayout());
        content.add(panel,BorderLayout.CENTER);
        content.repaint();
        content.revalidate();
    }
    public void setTheme(){
        active = new java.awt.Color(102,102,102);
        normal = new java.awt.Color(51,51,51);
        hover = new java.awt.Color(153,153,153);
        click = new java.awt.Color(204,204,204);
    }
    public void active(HighlightPanel panel){
        disable();
        actived=panel;
        actived.setColor(active);
    }
    public void disable(){
        if(actived!=null){
            actived.setColor(normal);
        }
    }
    private HighlightPanel actived;
    private Color active,normal,hover,click;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel app;
    private view.component.HighlightPanel bannedOp;
    private javax.swing.JPanel body;
    private view.component.HighlightPanel checkinOp;
    private javax.swing.JPanel content;
    private view.component.HighlightPanel deviceOp;
    private javax.swing.JPanel header;
    private view.component.imageIcon imageIcon15;
    private view.component.imageIcon imageIcon16;
    private view.component.imageIcon imageIcon2;
    private view.component.imageIcon imageIcon4;
    private view.component.imageIcon imageIcon5;
    private view.component.imageIcon imageIcon6;
    private view.component.imageIcon imageIcon7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel menuBar;
    private view.component.HighlightPanel statisticOp;
    private view.component.HighlightPanel userOp;
    // End of variables declaration//GEN-END:variables
}
