/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.page;

import bus.ThongKeBUS;
import constants.ResponseStatus;
import java.awt.Color;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.ThongTinSD;
import utils.DateTimeUtils;
import utils.Response;
import view.component.ChartPie;
import view.component.ModelChartPie;
import view.component.Model_Card;

/**
 *
 * @author Son
 */
public class ThongKePage extends javax.swing.JPanel {
    private final ThongKeBUS thongKeBUS;
    /**
     * Creates new form userPage
     */
    public ThongKePage() {
        initComponents();
        thongKeBUS = new ThongKeBUS();
        LocalDateTime startTime = LocalDateTime.now();
        startTime = startTime.with(LocalTime.MIN);
        LocalDateTime endTime = startTime.with(LocalTime.MAX);
        Date startDate = java.sql.Timestamp.valueOf(startTime);
        Date endDate = java.sql.Timestamp.valueOf(endTime);
        start.setDate(startDate);
        end.setDate(endDate);
        table.setTableHeader(null);
        setTable();
        setChart(startTime, endTime);
        setCard(startTime, endTime);
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        card1 = new view.component.Card();
        card2 = new view.component.Card();
        card5 = new view.component.Card();
        jPanel1 = new javax.swing.JPanel();
        start = new com.toedter.calendar.JDateChooser();
        end = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        confirmBtn1 = new view.component.Button();
        roundPanel1 = new view.component.RoundPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        conditionCb = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        keywordTxt = new javax.swing.JTextField();
        confirmBtn2 = new view.component.Button();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        nullText2 = new javax.swing.JLabel();
        nullText1 = new javax.swing.JLabel();
        chartPie1 = new view.component.ChartPie();
        chartPie2 = new view.component.ChartPie();

        setBackground(new java.awt.Color(200, 227, 254));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        card1.setColor1(new java.awt.Color(0, 0, 255));
        card1.setColor2(new java.awt.Color(153, 153, 255));
        add(card1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 237, 342, -1));

        card2.setColor1(new java.awt.Color(0, 153, 0));
        card2.setColor2(new java.awt.Color(0, 255, 204));
        add(card2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 402, 342, -1));

        card5.setColor1(new java.awt.Color(255, 204, 204));
        card5.setColor2(new java.awt.Color(153, 0, 0));
        add(card5, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 567, 342, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        start.setBackground(new java.awt.Color(255, 255, 255));

        end.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Bắt đầu:");

        jLabel2.setText("Kết thúc:");

        confirmBtn1.setBackground(new java.awt.Color(204, 204, 255));
        confirmBtn1.setColor(new java.awt.Color(204, 204, 255));
        confirmBtn1.setColorClick(new java.awt.Color(153, 153, 153));
        confirmBtn1.setColorOver(new java.awt.Color(102, 102, 102));
        confirmBtn1.setLabel("Xác nhận");
        confirmBtn1.setRadius(5);
        confirmBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmBtn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 46, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(start, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(confirmBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(end, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(47, 47, 47))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(start, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(end, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(confirmBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 46, -1, 179));

        roundPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("Hôm nay có gì ?");

        jLabel3.setText("Điều kiện:");

        conditionCb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Đã trả", "chưa trả" }));
        conditionCb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conditionCbActionPerformed(evt);
            }
        });

        jLabel4.setText("Tên Thiết bị:");

        confirmBtn2.setBackground(new java.awt.Color(204, 204, 255));
        confirmBtn2.setText("Tìm kiếm");
        confirmBtn2.setColor(new java.awt.Color(204, 204, 255));
        confirmBtn2.setColorClick(new java.awt.Color(153, 153, 153));
        confirmBtn2.setColorOver(new java.awt.Color(102, 102, 102));
        confirmBtn2.setRadius(5);
        confirmBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmBtn2ActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setText("Mã TB");

        jLabel6.setText("Tên thiết bị");

        jLabel7.setText("Mô tả");

        jSeparator1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel9.setText("TG mượn");

        jLabel10.setText("TG trả");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1)
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel5)
                .addGap(129, 129, 129)
                .addComponent(jLabel6)
                .addGap(98, 98, 98)
                .addComponent(jLabel7)
                .addGap(106, 106, 106)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 114, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(91, 91, 91))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(null);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã TB", "Tên", "Mô tả", "TG mượn", "TG trả"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.setFocusable(false);
        table.setGridColor(new java.awt.Color(216, 216, 216));
        table.setRowHeight(50);
        table.setSelectionBackground(new java.awt.Color(56, 138, 112));
        table.setShowHorizontalLines(true);
        table.setUpdateSelectionOnSort(false);
        jScrollPane1.setViewportView(table);

        javax.swing.GroupLayout roundPanel1Layout = new javax.swing.GroupLayout(roundPanel1);
        roundPanel1.setLayout(roundPanel1Layout);
        roundPanel1Layout.setHorizontalGroup(
            roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(roundPanel1Layout.createSequentialGroup()
                        .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addGroup(roundPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(conditionCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(roundPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(keywordTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(confirmBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        roundPanel1Layout.setVerticalGroup(
            roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(conditionCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(keywordTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(confirmBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        add(roundPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(354, 237, 806, 484));

        nullText2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        nullText2.setText("Chưa có dữ liệu thời gian này");
        add(nullText2, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 130, -1, 20));

        nullText1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        nullText1.setText("Chưa có dữ liệu thời gian này");
        add(nullText1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 130, -1, 20));
        add(chartPie1, new org.netbeans.lib.awtextra.AbsoluteConstraints(354, 46, 400, -1));
        add(chartPie2, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 46, 400, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void confirmBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmBtn1ActionPerformed
        LocalDateTime startTime = start.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDateTime();
        LocalDateTime endTime = end.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDateTime();
        endTime = endTime.with(LocalTime.MAX);
        if(startTime.isAfter(endTime)){
            JOptionPane.showMessageDialog(null, "ngày bắt đầu phải bé hơn ngày kết thúc", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        setChart(startTime, endTime);
        setCard(startTime, endTime);
        
    }//GEN-LAST:event_confirmBtn1ActionPerformed

    private void conditionCbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conditionCbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_conditionCbActionPerformed

    private void confirmBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmBtn2ActionPerformed
        setTable();
    }//GEN-LAST:event_confirmBtn2ActionPerformed
    public void setTable(){
        String keyword = keywordTxt.getText();
        Response<List<ThongTinSD>> response= null;
        if(conditionCb.getSelectedIndex()==0){
            response = thongKeBUS.timThietBiDaTraTrongHomNay(keyword);
        }
        else 
            response = thongKeBUS.timThietBiChuaTra(keyword);
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        model.setRowCount(0);
        for(ThongTinSD thongTinSD: response.getData()){
            Object[] row = new Object[]{thongTinSD.getThietBi().getMaTB(),thongTinSD.getThietBi().getTenTB(),
            thongTinSD.getThietBi().getMoTaTB(),DateTimeUtils.format(thongTinSD.getTGMuon()),
            DateTimeUtils.format(thongTinSD.getTGTra())};
            model.addRow(row);
        }
    }
    public void setCard(LocalDateTime startTime,LocalDateTime endTime){
        Response<Long> response = thongKeBUS.thongKeSoLuongXLChuaXuLi(startTime, endTime);
        if(response.getStatus()==ResponseStatus.FAILURE){
            return;
        }
        card1.setData(new Model_Card("Vi phạm chưa xử lý",response.getData()+""));
        Response<Object[]> response1 = thongKeBUS.thongKeSoLuongXLDaXuLi(startTime, endTime);
        if(response1.getStatus()==ResponseStatus.FAILURE){
            return;
        }
        Object[] data = response1.getData();
        long soLuongVP = (long)data[0];
        double soTien;
        if(data[1]==null){
            soTien = 0;
        }
        else{
           long soTienLong = (long) data[1]; // Assuming data[1] is a long
            soTien = (double) soTienLong;}
        card2.setData(new Model_Card("Vi phạm đã xử lý",soLuongVP+""));
        card5.setData(new Model_Card("Tổng số tiền bồi thường",soTien+""));
    }
    
    public void setChart(LocalDateTime startTime,LocalDateTime endTime){
        Response<List<Object[]>> response =  thongKeBUS.thongKeSoLuongTVTheoKhoa(startTime, endTime);
        if(response.getStatus()==ResponseStatus.FAILURE){
            return;
        }
          nullText1.setVisible(false);
        List<ModelChartPie> list = createChartModel(response.getData());
        setModel(chartPie1,list);
        if(response.getData().isEmpty())
            nullText1.setVisible(true);
        else 
            nullText1.setVisible(false);
        response = thongKeBUS.thongKeSoLuongTVTheoNganh(startTime, endTime);
        if(response.getStatus()==ResponseStatus.FAILURE){
            return;
        }
        list = createChartModel(response.getData());
        setModel(chartPie2, list);
                if(response.getData().isEmpty())
            nullText2.setVisible(true);
        else 
            nullText2.setVisible(false);
    }
    
    public  List<ModelChartPie> createChartModel(List<Object[]> data){
        List<ModelChartPie> chartData = new ArrayList<>();
        Random random = new Random();
        for (Object[] row : data) {
            String title = (String) row[0];
            double value =  ((Long) row[1]).doubleValue();
            Color color = new Color(random.nextInt(256), random.nextInt(256), random.nextInt(256));
            System.out.println(value);
            chartData.add(new ModelChartPie(title, value, color));
        }
        return chartData;
    }
    public void setModel(ChartPie chartPie,List<ModelChartPie> list){
        chartPie.setModel(list);
        chartPie.revalidate();
        chartPie.repaint();
    }
    public void setNull(ChartPie chartPie){
        List<ModelChartPie> chartData = new ArrayList<>();
        chartData.add(new ModelChartPie("Trống", 0, new Color(153,0,0)));
        setModel(chartPie, chartData);

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private view.component.Card card1;
    private view.component.Card card2;
    private view.component.Card card5;
    private view.component.ChartPie chartPie1;
    private view.component.ChartPie chartPie2;
    private javax.swing.JComboBox<String> conditionCb;
    private view.component.Button confirmBtn1;
    private view.component.Button confirmBtn2;
    private com.toedter.calendar.JDateChooser end;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField keywordTxt;
    private javax.swing.JLabel nullText1;
    private javax.swing.JLabel nullText2;
    private view.component.RoundPanel roundPanel1;
    private com.toedter.calendar.JDateChooser start;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
